import { Rate, RateTypes } from '../app/schema'
import { Achieva, FirstFed } from '../store/lender-info'

export const AchievaRate: Rate = {
  id: 'achieva-rate',
  monthly_payment_cents: 38000,
  rate_bp: 200,
  rate_type: RateTypes.Fixed,
  term_years: 5,
  url: 'https://splashfinancial.com',
  apr: 2.83,
  ach_discount: 0,
  discountedRate: 2.56,
  isExpired: false,
  origination_fee: 500,
  netDisbursedAmount: 19000,
  netDisbursedAmountCents: 1900000,
  totalLoanAmount: 20000,
  totalLoanAmountCents: 1000000,
  ach_discount_bp: 0,
  discountedRateBp: 0,
  origination_fee_cents: 0,
  total_finance_charge_cents: 0,
  total_interest_paid_cents: 0,
  total_loan_amount_cents: 0,
  total_loan_cost_cents: 0,
  is_topup_offer: true,
  maximum_loan_amount: 10000,
  minimum_loan_amount: 0,
  borrower_rate_guid: '123',
  interest_rate: 4.5,
  lender: Achieva,
  top_up_loan_amount: 100,
  total_loan_amount: 90000,
  monthly_payment: 1677.87,
  total_interest_paid: 0,
  total_loan_cost: 0,
  total_finance_charge: 1200,
  degree_type: null,
  disclosures: null,
  margin: null,
  selected: false,
  tier: null
}

export const FirstFedRate: Rate = {
  id: 'first-fed-rate',
  monthly_payment_cents: 38000,
  rate_bp: 200,
  rate_type: RateTypes.Fixed,
  term_years: 5,
  url: 'https://splashfinancial.com',
  apr: 2.83,
  ach_discount: 0,
  discountedRate: 2.56,
  isExpired: false,
  origination_fee: 500,
  netDisbursedAmount: 19000,
  netDisbursedAmountCents: 1900000,
  totalLoanAmount: 20000,
  totalLoanAmountCents: 1000000,
  ach_discount_bp: 0,
  discountedRateBp: 0,
  origination_fee_cents: 0,
  total_finance_charge_cents: 0,
  total_interest_paid_cents: 0,
  total_loan_amount_cents: 0,
  total_loan_cost_cents: 0,
  is_topup_offer: true,
  maximum_loan_amount: 10000,
  minimum_loan_amount: 0,
  borrower_rate_guid: '123',
  interest_rate: 4.5,
  lender: FirstFed,
  top_up_loan_amount: 100,
  total_loan_amount: 90000,
  monthly_payment: 1677.87,
  total_interest_paid: 0,
  total_loan_cost: 0,
  total_finance_charge: 1200,
  degree_type: null,
  disclosures: null,
  margin: null,
  selected: false,
  tier: null
}

export const offers = [{ ...FirstFedRate }, { ...AchievaRate }] as Rate[]
